if: tag IS blank
language: node_js
node_js: '10.16'
cache: yarn
os:
  - linux
  - windows

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    function npm_tag() {
      if [[ "$TRAVIS_BRANCH" = "master" ]];
      then
        echo "latest"
      else
        echo "next"
      fi
    }

install:
  - yarn --offline

before_script:
  - yarn lint
  - yarn coverage
  - yarn coverage-report
  - yarn bump-version

script:
  - yarn build

deploy:
  provider: npm
  email: dan@dandoes.net
  skip_cleanup: true
  api_key: $NPM_TOKEN
  tag: $(npm_tag)
  on:
    repo: DanielSchaffer/webpack-babel-multi-target-plugin
    all_branches: true
    condition: $TRAVIS_OS_NAME = "linux" && $TRAVIS_BRANCH =~ ^master|release\/[0-9]+\.[0-9]+\.[0-9]$

after_deploy:
  - ./script/push
